ext.excludedClasses = [
        // android
        '*.R',
        '*.R$*',
        '*.BuildConfig',
        '*.Manifest*',
        'android.*.*.*',
        // dagger
        '*.*_MembersInjector',
        '*.Dagger*Component',
        '*.Dagger*Component$Builder',
        '*.*Module_*Factory',
        '*.di.module.*',
        '*.*_Factory*',
        '*.*Module*',
        '*.*Dagger*',
        '*.*Hilt*',
        '*.*GeneratedInjector*',
        '*.codegen.*',
        '*.*_Impl*',
        // kotlin
        '*.*Component*',
        '*.*BR*',
        '*.*$Lambda$*',
        '*.*Companion*',
        '*.*MembersInjector*',
        '*.*_Provide*Factory*',
        '*.*Extensions*',
        // Pera
        '*.di.*',
        '*.domain.model.*',
        '*.data.model.*',
        '*.data.service.*',
        '*.database.model.*',
        '*.database.dao.*',
        '*PeraResult*'
]
ext.excludedPackages = [
        'com.algorand.wallet.viewmodel'
]
