build:
  maxIssues: 0

processors:
  active: true
  exclude: [ ]

console-reports:
  active: true
  exclude: [ ]

output-reports:
  active: true
  exclude: [ ]

comments:
  active: true
  excludes: "**/*Test.kt, **/*Spec.kt, **/test/**, **/generated/**"
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  EndOfSentenceFormat:
    active: false
    endOfSentenceFormat: ([.?!][ \t\n\r\f<])|([.?!]$)
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 5
  ComplexInterface:
    active: false
    threshold: 10
  CyclomaticComplexMethod:
    active: true
    threshold: 50
    ignoreSingleWhenExpression: false
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    threshold: 500
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
  MethodOverloading:
    active: false
    threshold: 6
  NestedBlockDepth:
    active: true
    threshold: 5
  StringLiteralDuplication:
    active: false
    excludes: "**/*Test.kt, **/*Spec.kt, **/test/**, **/generated/**"
    threshold: 3
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  TooManyFunctions:
    active: true
    excludes: "**/*Test.kt, **/*Spec.kt, **/test/**, **/generated/**, **/ViewModelModule.kt, **/BuildersModule.kt"
    thresholdInFiles: 20
    thresholdInClasses: 30
    thresholdInInterfaces: 50
    thresholdInObjects: 11
    thresholdInEnums: 11

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(ignore|expected).*"
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames:
      - toString
      - hashCode
      - equals
      - finalize
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: false
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: false
  SwallowedException:
    active: false
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
    exceptions:
      - IllegalArgumentException
      - IllegalStateException
      - IOException
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionCaught:
    active: false
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
  TooGenericExceptionThrown:
    active: false
    exceptionNames:
      - Error
      - Exception
      - Throwable
      - RuntimeException

formatting:
  autoCorrect: true

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z][_a-zA-Z0-9]*'
  ForbiddenClassName:
    active: false
    forbiddenName: [ ]
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: false
    minimumFunctionNameLength: 3
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
    functionPattern: '^([a-z$][a-zA-Z$0-9]*)|(`.*`)$'
  MatchingDeclarationName:
    active: true
  MemberNameEqualsClassName:
    active: false
    ignoreOverridden: true
  ObjectPropertyNaming:
    active: true
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z\d]*'
    privatePropertyPattern: '(_)?[a-z][A-Za-z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
    excludes: "**/*Test.kt, **/*Spec.kt, **/test/**, **/generated/**"
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: false
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  InvalidRange:
    active: false
  IteratorHasNextCallsNextMethod:
    active: false
  IteratorNotThrowingNoSuchElementException:
    active: false
  LateinitUsage:
    active: false
    excludes: "**/*Test.kt, **/*Spec.kt, **/test/**, **/generated/**"
    ignoreAnnotated: [ ]
    ignoreOnClassesPattern: ""
  UnconditionalJumpStatementInLoop:
    active: false
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: false
  UselessPostfixExpression:
    active: false
  WrongEqualsTypeParameter:
    active: false

style:
  active: true
  CollapsibleIfStatements:
    active: false
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix:
      - to
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: false
    comments:
      - FIXME:
      - STOPSHIP:
  ForbiddenImport:
    active: false
    imports: [ ]
  FunctionOnlyReturningConstant:
    active: false
    ignoreOverridableFunction: true
    excludedFunctions:
      - describeContents
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: true
    excludes: "**/*Test.kt, **/*Spec.kt, **/test/**, **/generated/**"
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
    ignoreHashCodeFunction: false
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
  MaxLineLength:
    active: true
    excludes: "**/*Test.kt, **/*Spec.kt, **/test/**, **/generated/**, **/ViewModelModule.kt, **/BuildersModule.kt"
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  MayBeConst:
    active: true
  ModifierOrder:
    active: true
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  BracesOnWhenStatements:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  ReturnCount:
    active: true
    max: 5
    excludedFunctions:
      - equals
      - getItemViewType
  SafeCast:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    active: true
    max: 5
  UnnecessaryAbstractClass:
    active: true
  WildcardImport:
    active: true
    excludeImports:
      - java.util.*
      - kotlinx.android.synthetic.*