package com.algorand.android.ui.compose.theme

import androidx.compose.ui.graphics.Color

@Suppress("MagicNumber")
object PeraColor {
    val primaryLight = Color(0xFF646115)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF27272A)
    val onPrimaryContainerLight = Color(0xFFFFFFFF)
    val secondaryLight = Color(0xFF625F42)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFF1F1F2)
    val onSecondaryContainerLight = Color(0xFF18181B)
    val tertiaryLight = Color(0xFF3F6655)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFC1ECD6)
    val onTertiaryContainerLight = Color(0xFF274E3E)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFEF9EB)
    val onBackgroundLight = Color(0xFF1D1C14)
    val surfaceLight = Color(0xFFF1F1F2)
    val onSurfaceLight = Color(0xFF71717A)
    val surfaceVariantLight = Color(0xFFE7E3D1)
    val onSurfaceVariantLight = Color(0xFF49473A)
    val outlineLight = Color(0xFF7A7768)
    val outlineVariantLight = Color(0xFFCAC7B5)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF323128)
    val inverseOnSurfaceLight = Color(0xFFF5F1E3)
    val inversePrimaryLight = Color(0xFFCFCA74)
    val surfaceDimLight = Color(0xFFDEDACD)
    val surfaceBrightLight = Color(0xFFFEF9EB)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF8F3E6)
    val surfaceContainerLight = Color(0xFFF2EEE0)
    val surfaceContainerHighLight = Color(0xFFECE8DB)
    val surfaceContainerHighestLight = Color(0xFFE6E2D5)

    val primaryDark = Color(0xFFCFCA74)
    val onPrimaryDark = Color(0xFF343200)
    val primaryContainerDark = Color(0xFFFFEE55)
    val onPrimaryContainerDark = Color(0xFF18181B)
    val secondaryDark = Color(0xFFCCC8A4)
    val onSecondaryDark = Color(0xFF333118)
    val secondaryContainerDark = Color(0xFF27272A)
    val onSecondaryContainerDark = Color(0xFFF1F1F2)
    val tertiaryDark = Color(0xFFA5D0BA)
    val onTertiaryDark = Color(0xFF0D3728)
    val tertiaryContainerDark = Color(0xFF274E3E)
    val onTertiaryContainerDark = Color(0xFFC1ECD6)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF14140C)
    val onBackgroundDark = Color(0xFFE6E2D5)
    val surfaceDark = Color(0xFF27272A)
    val onSurfaceDark = Color(0xFF71717A)
    val surfaceVariantDark = Color(0xFF49473A)
    val onSurfaceVariantDark = Color(0xFFCAC7B5)
    val outlineDark = Color(0xFF949181)
    val outlineVariantDark = Color(0xFF49473A)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE6E2D5)
    val inverseOnSurfaceDark = Color(0xFF323128)
    val inversePrimaryDark = Color(0xFF646115)
    val surfaceDimDark = Color(0xFF14140C)
    val surfaceBrightDark = Color(0xFF3B3930)
    val surfaceContainerLowestDark = Color(0xFF0F0E07)
    val surfaceContainerLowDark = Color(0xFF1D1C14)
    val surfaceContainerDark = Color(0xFF212018)
    val surfaceContainerHighDark = Color(0xFF2B2A21)
    val surfaceContainerHighestDark = Color(0xFF36352C)
}
