name: "Android App Checks"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  android-build:
    name: "Android App Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"
      - name: "Run KtLint"
        run: ./gradlew ktlint
      - name: "Run Detekt"
        run: ./gradlew detekt
      - name: "Archive App Lint Test Results"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: "app-lint-results"
          path: ./**/build/reports/**
          overwrite: true
      - name: "Run Unit Tests"
        run: ./gradlew testDebugUnitTest
      - name: "Archive App Unit Tests Report"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: "app-unit-tests-results"
          path: ./**/build/reports/**
          overwrite: true
      - name: "Update packages"
        run: sudo apt-get update
      - name: "Install xmlstarlet"
        run: sudo apt-get install xmlstarlet
      - name: "Generate Report and Validate Coverage"
        run: ./common-sdk/test-coverage/testCoverage.sh
      - name: "Archive Test Coverage Results"
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: "test-coverage-result"
          path: ./common-sdk/build/reports/kover/**
          overwrite: true
      - name: "Build Prod Debug Bundle"
        run: ./gradlew packageProdDebugBundle
