apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 1
  metadata:
      tags:
        - e2e
        - release team
        - other tag
      build: Release $CI_COMMIT_SHORT_SHA
espresso:
  app: ./app/build/outputs/apk/prod/debug/app-prod-debug.apk
  testApp: ./app/build/outputs/apk/androidTest/prod/debug/app-prod-debug-androidTest.apk
suites:
  - name: "Main Suite"
    emulators:
      - name: Android GoogleAPI Emulator
        platformVersions:
          - "14.0"
    devices:
      - name: "Google.*"
        platformVersion: "14"
      - name: "Samsung.*"
        platformVersion: "13"
    testOptions:
      visualCheck: $VISUAL_CHECK


# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
